#!/bin/bash
ARCH=`uname -a | awk '{print $13}'`
if ! [[ "$ARCH" == armv* ]]
then
    echo "Script should be run on an armv architecture"
    exit 1
fi
DOCKERFILE=Dockerfile-rpi
TAG=rpi-builder-latest
docker build -f $DOCKERFILE --pull --force-rm=true --rm=true -t apendergast/alpine-node:$TAG .
